version: '3.8'
services:
  my-nginx-app:
    build: .
    image: gonzat/tpfinal:latest
    ports:
      - "8080:80"
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 5
