name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-nginx-app .

      - name: Run container
        run: |
          docker run -d -p 8080:80 my-nginx-app

      - name: Test container
        run: |
          curl -I http://localhost:8080

